/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as GamesSlotsImport } from './routes/games/slots'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GamesSlotsRoute = GamesSlotsImport.update({
  path: '/games/slots',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/games/slots': {
      id: '/games/slots'
      path: '/games/slots'
      fullPath: '/games/slots'
      preLoaderRoute: typeof GamesSlotsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/slots': typeof GamesSlotsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/slots': typeof GamesSlotsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/games/slots': typeof GamesSlotsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games/slots'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games/slots'
  id: '__root__' | '/' | '/games/slots'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesSlotsRoute: typeof GamesSlotsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesSlotsRoute: GamesSlotsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/games/slots"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/games/slots": {
      "filePath": "games/slots.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
